language: node_js
node_js:
  - "11"
cache: yarn

before_script:
  - npm install --save @angular/material @angular/cdk @angular/animations
script:
  - yarn lint
  - yarn test --watch=false --browsers=ChromeHeadless
  - yarn build --prod
