export enum IdeaCategory {
  HELP_FOR_OTHERS = 'HELP_FOR_OTHERS',
  TIME_FOR_ENVIRONMENT = 'TIME_FOR_ENVIRONMENT',
  TIME_FOR_KNOWLEDGE = 'TIME_FOR_KNOWLEDGE',
  TIME_FOR_COMMUNITIES = 'TIME_FOR_COMMUNITIES',
  VOLUNTEERING = 'VOLUNTEERING'
}
